### ISSUE TITLE
HR fails when watchOptions.exclude includes cacheDir

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#16]
`"reboost": "0.9.1"`

**reboost.js**

```js
const { start } = require('reboost');

start({
  entries: [
    ['./src/index.js', './public/dist/index.js']
  ],
  contentServer: {
    root: './public',
    open: true
  },
  watchOptions: {
    include: /.*/,
    exclude: /\.config|\.reboost_cache|node_modules/,
    chokidar: {}
  }
});
```
In this case, page auto-reloading does fail. If it is right, documentation should mention that.

**Comment by sarsamurmu** [comment]
Can you check it again with the latest version (`0.10.0`)?

**Comment by GHNewbiee** [comment]
Yes, it does work with default options as well as mu modified options. Well done!

**Comment by GHNewbiee** [comment]
When it starts for first time after booting, I get the following error. After a couple times of web page reloading, I continue getting the same error. Moreover, `lit-element`s never gets rendered.

```bash
$ node reboost.js
[reboost] Plugin change detected, clearing cached files...
[reboost] Clear cache complete
[reboost] Starting proxy server...
[reboost] Generated: ./src/index.js -> ./public/dist/index.js
[reboost] Proxy server started
[reboost] Content server started at: http://localhost:8000
[reboost] Content server started at: http://192.168.1.53:8001

  Error: ENOENT: no such file or directory, open '.../reboost-le/.reboost_cache/files/2d19f0273042a924a4c98d7656d424dd'
      at Object.openSync (fs.js:465:3)
      at Object.readFileSync (fs.js:368:35)
      at .../reboost-le/node_modules/reboost/dist/node/file-handler.js:156:107
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cors (.../reboost-le/node_modules/@koa/cors/index.js:98:16)

(node:20536) Warning: Label 'Response time - src/index.js' already exists for console.time()
(Use `node --trace-warnings ...` to show where the warning was created)

  Error: ENOENT: no such file or directory, open '.../reboost-le/.reboost_cache/files/2d19f0273042a924a4c98d7656d424dd'
      at Object.openSync (fs.js:465:3)
      at Object.readFileSync (fs.js:368:35)
      at .../reboost-le/node_modules/reboost/dist/node/file-handler.js:156:107
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cors (.../reboost-le/node_modules/@koa/cors/index.js:98:16)

(node:20536) Warning: Label 'Response time - src/index.js' already exists for console.time()

  Error: ENOENT: no such file or directory, open '.../reboost-le/.reboost_cache/files/2d19f0273042a924a4c98d7656d424dd'
      at Object.openSync (fs.js:465:3)
      at Object.readFileSync (fs.js:368:35)
      at .../reboost-le/node_modules/reboost/dist/node/file-handler.js:156:107
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cors (.../reboost-le/node_modules/@koa/cors/index.js:98:16)

(node:20536) Warning: Label 'Response time - src/index.js' already exists for console.time()

  Error: ENOENT: no such file or directory, open '.../reboost-le/.reboost_cache/files/2d19f0273042a924a4c98d7656d424dd'
      at Object.openSync (fs.js:465:3)
      at Object.readFileSync (fs.js:368:35)
      at .../reboost-le/node_modules/reboost/dist/node/file-handler.js:156:107
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cors (.../reboost-le/node_modules/@koa/cors/index.js:98:16)
```
After restarting
```bash
^C
$ node reboost.js
```
(but not rebooting), everything works fine.

**Comment by GHNewbiee** [comment]
Yes, it does work fine.
