### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by GHNewbiee** [sarsamurmu/reboost#23]
When it starts for first time after booting, I get the following error. After a couple of times of page reloading, I continue getting the same error. Moreover, `lit-element` never gets rendered.

```bash
$ node reboost.js
[reboost] Plugin change detected, clearing cached files...
[reboost] Clear cache complete
[reboost] Starting proxy server...
[reboost] Generated: ./src/index.js -> ./public/dist/index.js
[reboost] Proxy server started
[reboost] Content server started at: http://localhost:8000
[reboost] Content server started at: http://192.168.1.53:8001

  Error: ENOENT: no such file or directory, open '.../reboost-le/.reboost_cache/files/2d19f0273042a924a4c98d7656d424dd'
      at Object.openSync (fs.js:465:3)
      at Object.readFileSync (fs.js:368:35)
      at .../reboost-le/node_modules/reboost/dist/node/file-handler.js:156:107
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cors (.../reboost-le/node_modules/@koa/cors/index.js:98:16)

(node:20536) Warning: Label 'Response time - src/index.js' already exists for console.time()
(Use `node --trace-warnings ...` to show where the warning was created)

  Error: ENOENT: no such file or directory, open '.../reboost-le/.reboost_cache/files/2d19f0273042a924a4c98d7656d424dd'
      at Object.openSync (fs.js:465:3)
      at Object.readFileSync (fs.js:368:35)
      at .../reboost-le/node_modules/reboost/dist/node/file-handler.js:156:107
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cors (.../reboost-le/node_modules/@koa/cors/index.js:98:16)

(node:20536) Warning: Label 'Response time - src/index.js' already exists for console.time()

  Error: ENOENT: no such file or directory, open '.../reboost-le/.reboost_cache/files/2d19f0273042a924a4c98d7656d424dd'
      at Object.openSync (fs.js:465:3)
      at Object.readFileSync (fs.js:368:35)
      at .../reboost-le/node_modules/reboost/dist/node/file-handler.js:156:107
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cors (.../reboost-le/node_modules/@koa/cors/index.js:98:16)

(node:20536) Warning: Label 'Response time - src/index.js' already exists for console.time()

  Error: ENOENT: no such file or directory, open '.../reboost-le/.reboost_cache/files/2d19f0273042a924a4c98d7656d424dd'
      at Object.openSync (fs.js:465:3)
      at Object.readFileSync (fs.js:368:35)
      at .../reboost-le/node_modules/reboost/dist/node/file-handler.js:156:107
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async cors (.../reboost-le/node_modules/@koa/cors/index.js:98:16)
```
After restarting (2nd start)
```bash
^C
$ node reboost.js
```
(but not rebooting), I get the following:
```bash
$ node reboost.js
[reboost] Refreshing cache...
[reboost] Refresh cache complete
[reboost] Starting proxy server...
[reboost] Generated: ./src/index.js -> ./public/dist/index.js
[reboost] Proxy server started
[reboost] Content server started at: http://localhost:8000
[reboost] Content server started at: http://192.168.1.53:8001
(node:25094) Warning: Label 'Response time - src/index.js' already exists for console.time()
(Use `node --trace-warnings ...` to show where the warning was created)
Response time - src/index.js: 1.302s
(node:25094) Warning: No such label 'Response time - src/index.js' for console.timeEnd()
(node:25094) Warning: Label 'Response time - node_modules/lit-element/lit-element.js' already exists for console.time()
Response time - node_modules/lit-element/lit-element.js: 791.467ms
(node:25094) Warning: No such label 'Response time - node_modules/lit-element/lit-element.js' for console.timeEnd()
Response time - node_modules/lit-element/lib/updating-element.js: 776.126ms
...
(node:25094) Warning: Label 'Response time - node_modules/lit-html/lib/default-template-processor.js' already exists for console.time()
Response time - node_modules/lit-html/lib/directive.js: 234.986ms
Response time - node_modules/lit-html/lib/default-template-processor.js: 298.26ms
(node:25094) Warning: No such label 'Response time - node_modules/lit-html/lib/default-template-processor.js' for console.timeEnd()
Response time - node_modules/lit-html/lib/template-result.js: 270.865ms
...
```
`lit-element` is rendered.

After restarting (3rd start), no more errors, it works fine.

I have used the default `reboost.js` + `showResponseTime: true` in the default location. Latest updates.

**Comment by sarsamurmu** [comment]
These are probably fixed in the latest version
